### ISSUE TITLE
Why all copy paste

### ISSUE THREAD

**Issue by M100RE** [a-b-3-4/Abom#2]
Hello dear ab, i cannot unsee this. there is some copppieed code in your repositori. Why do yo do sis. Thats not your code man. Stop copy code. NOOOOOOOOOOOOOO! 
i have evidnec. 
https://yewtu.be/watch?v=meARMOmTLgE&list=PLlrATfBNZ98dC-V-N3m0Go4deliWHPFwT&index=4
look at tis link. it is evidenc. and not a virus.
please beliiiieve me. this man no good, stop him. he not doing good!!!!!!!?

**Comment by M100RE** [comment]
your arr very correct. because what you say is right. and i support your claims. because thei arr right. and not rong. and not copy paaaaste. please stop copy paste

**Comment by M100RE** [comment]
yeeeeeeees. you right. this is very copy paaste. please stop this man. he stole my grandmother

**Comment by M100RE** [comment]
#nocopypast

**Comment by azange** [comment]
Yes I noticed also very correct 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍💯💯💯💯💯💯💯💯💯💯💯💯💯💯

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
Diss is elligal
