### ISSUE TITLE
Not die yellow from sie egg

### ISSUE THREAD

**Issue by M100RE** [a-b-3-4/Abom#5]
Strg + c; strg + v

**Comment by M100RE** [comment]
So tru

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> Strg + c; strg + v

Tru

**Comment by M100RE** [comment]
> > Strg + c; strg + v
> 
> Tru

Tru

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> Tru

Tru

**Comment by M100RE** [comment]
> > Tru
> 
> Tru

Tru

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> > > Tru
> > 
> > 
> > Tru
> 
> Tru

Tru

**Comment by M100RE** [comment]
> > > > Tru
> > > 
> > > 
> > > Tru
> > 
> > 
> > Tru
> 
> Tru

Tru

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> > > > > Tru
> > > > 
> > > > 
> > > > Tru
> > > 
> > > 
> > > Tru
> > 
> > 
> > Tru
> 
> Tru

Tru

**Comment by M100RE** [comment]
> > > > > > Tru
> > > > > 
> > > > > 
> > > > > Tru
> > > > 
> > > > 
> > > > Tru
> > > 
> > > 
> > > Tru
> > 
> > 
> > Tru
> 
> Tru

Tru

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> > > > > > > Tru
> > > > > > 
> > > > > > 
> > > > > > Tru
> > > > > 
> > > > > 
> > > > > Tru
> > > > 
> > > > 
> > > > Tru
> > > 
> > > 
> > > Tru
> > 
> > 
> > Tru
> 
> Tru

Rly tru
