### ISSUE TITLE
Howwe do i mak mc lodeston my friend wont sop laghing at me:(

### ISSUE THREAD

**Issue by BrudaLukasZiehmlichCringeCopyPastedEinf** [a-b-3-4/Abom#8]

**Comment by M100RE** [comment]
Idunno me frind too laaf at I. But me wont be bullyd anymoa. I Gonna resistance. Let fight againdt These nasti dictadors

**Comment by BrudaLukasZiehmlichCringeCopyPastedEinf** [comment]
> Idunno me frind too laaf at I. But me wont be bullyd anymoa. I Gonna resistance. Let fight againdt These nasti dictadors

Jes
